# Generated by Django 5.1.4 on 2025-01-27 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_licensehold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=30, unique=True)),
                ('application_date', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=100)),
                ('renewal_year', models.CharField(max_length=9)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.licensedetails')),
            ],
        ),
    ]
