# Generated by Django 5.1.4 on 2025-01-28 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='license',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.licensedetails'),
        ),
    ]
