# Generated by Django 5.1.4 on 2025-01-18 14:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_userdetails_user_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='last_requested_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='licensedetails',
            name='district_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='licensedetails',
            name='establishment_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='licensedetails',
            name='licensee_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='licensedetails',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='licensedetails',
            name='yearly_license_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='AddressDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_station', models.CharField(max_length=100)),
                ('excise_sub_division', models.CharField(max_length=100)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('site_address', models.TextField()),
                ('land_details', models.TextField(blank=True, null=True)),
                ('block', models.CharField(blank=True, max_length=100, null=True)),
                ('road', models.CharField(blank=True, max_length=100, null=True)),
                ('license_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_details', to='login.licensedetails')),
            ],
        ),
        migrations.CreateModel(
            name='MemberDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_status', models.CharField(choices=[('Partner', 'Partner'), ('Member', 'Member')], max_length=50)),
                ('member_name', models.CharField(max_length=100)),
                ('citizenship', models.CharField(choices=[('Indian', 'Indian'), ('Non-Indian', 'Non-Indian')], default='Indian', max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('pan_number', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='login.licensedetails')),
            ],
        ),
        migrations.CreateModel(
            name='MGQDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MGQ_in_BL', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MGQ_in_LPL', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MGQ_in_Quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deck_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('license_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mgq_details', to='login.licensedetails')),
            ],
        ),
        migrations.CreateModel(
            name='UnitDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licensee_type', models.CharField(max_length=50)),
                ('reg_office_address', models.TextField(blank=True, null=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN number (e.g., ABCDE1234F).', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')])),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number.', regex='^\\d{10}$')])),
                ('date_of_incorporation', models.DateField(blank=True, null=True)),
                ('department_office_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('cin_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('license_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unit_details', to='login.licensedetails')),
            ],
        ),
    ]
