# Generated by Django 5.1.4 on 2025-01-18 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_otpverification_last_requested_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdetail',
            name='pan_number',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN number (e.g., ABCDE1234F).', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')]),
        ),
    ]
