# Generated by Django 5.1.4 on 2025-01-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_memberdetail_pan_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberdetail',
            old_name='license',
            new_name='license_details',
        ),
    ]
