# Generated by Django 5.1.4 on 2025-01-23 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_rename_license_memberdetail_license_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitdetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number starting with a digit between 6 and 9.', regex='^[6-9]{1}[0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number starting with a digit between 6 and 9.', regex='^[6-9]{1}[0-9]{9}$')]),
        ),
    ]
