# Generated by Django 5.1.4 on 2025-01-23 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_unitdetails_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitdetails',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid email address.', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
    ]
