# Generated by Django 5.1.4 on 2025-01-26 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_district_licensecategory_alter_unitdetails_email_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensedetails',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='licensedetails',
            name='license_category',
        ),
        migrations.RemoveField(
            model_name='licensedetails',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='memberdetail',
            name='license_details',
        ),
        migrations.RemoveField(
            model_name='unitdetails',
            name='license_details',
        ),
        migrations.RemoveField(
            model_name='mgqdetails',
            name='license_details',
        ),
        migrations.DeleteModel(
            name='AddressDetails',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='LicenseCategory',
        ),
        migrations.DeleteModel(
            name='MemberDetail',
        ),
        migrations.DeleteModel(
            name='UnitDetails',
        ),
        migrations.DeleteModel(
            name='LicenseDetails',
        ),
        migrations.DeleteModel(
            name='MGQDetails',
        ),
    ]
