# Generated by Django 5.1.4 on 2025-01-29 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_remove_licensedetails_district_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='last_requested_at',
        ),
    ]
